### PR TITLE
Limiting VS version to avoid AppVeyor failures.

### PR DESCRIPTION
**Pull request by whart222**

### CODE REVIEW

**Comment by pelson** [comment]
This is an interesting one @whart222. Is it the case that you always want to compile with a specific VS too? Are you aware of the `build/msvc_compiler` flag in the conda-build metadata? The line of interest is in https://github.com/conda/conda-build/blob/master/conda_build/windows.py#L210.

**Comment by irmen** [comment]
Pyro4 is a pure python library, why is there a need to fool around with visual studio runtime libraries?

**Comment by pelson** [comment]
A good question @irmen. @whart222 - do you have a link to the original discussion on this? I believe the problem build of vs was pulled by the Continuum folks, so this change may no longer be necessary.

**Comment by whart222** [comment]
I was only limiting the VS because an earlier comment suggested that this
might work around build failures.  I'll remove this restriction, and we can
see if the issue is resolved.

**Comment by jakirkham** [comment]
The original issue is this one ( https://github.com/conda-forge/staged-recipes/issues/666 ). It has since been resolved so this should be reverted, @whart222.

**Pull request merged**
